### ISSUE TITLE
Thesis help

### ISSUE THREAD

**Issue by xiao-sys** [har33sh/Dueling-Deep-Q-Learning#1]
I really appreciate your contribution, may I ask if these programs are the code in the paper? If so, could you please provide the title of the paper

**Comment by har33sh** [comment]
Yes, some part of this is used in the paper

@article{kumar2019explainable, title={Explainable ai: Deep reinforcement learning agents for residential demand side cost savings in smart grids}, author={Kumar, Hareesh and Mammen, Priyanka Mary and Ramamritham, Krithi}, journal={arXiv preprint arXiv:1910.08719}, year={2019} }

**Comment by har33sh** [comment]
Explainable ai: Deep reinforcement learning agents for residential demand side cost savings in smart grids
